### ISSUE TITLE
error on step 4

### ISSUE THREAD

**Issue by Deathkon** [inoerp/inoERP#114]
Fatal error: Uncaught Error: Call to undefined function create_function() in C:\xampp\htdocs\inoerp\engine\install\steps\complete_install.php:78 Stack trace: #0 C:\xampp\htdocs\inoerp\engine\install\steps\complete_install.php(20): getQueriesFromSQLFile('C:\\xampp\\htdocs...') #1 C:\xampp\htdocs\inoerp\engine\install\steps\complete_install.php(115): importSQL('C:\\xampp\\htdocs...', Object(dbc)) #2 C:\xampp\htdocs\inoerp\engine\install\install_template.php(38): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\inoerp\install.php(44): include_once('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\inoerp\engine\install\steps\complete_install.php on line 78

**Comment by priyank7191** [comment]
Please help here.. I am getting same error

**Comment by Deathkon** [comment]
> Please help here. I am getting the same error
am sorry, I don't know how to fix this error.
