### ISSUE TITLE
Sql. Error message:  unable to open database file:

### ISSUE THREAD

**Issue by victor365** [inoerp/inoERP#127]
I am getting this error

**Comment by inoerp** [comment]
Check your db connection details. Which version are you using

**Comment by maplewang** [comment]
windows 11 
mysql 8.0.15
sqlite dll copy to the oneapp_win.exe directory rikdata_erp.db

mysql dumped already.

from the error seems Is there anyway to choose mysql intead of sqlite? 

oneapp_win.exe
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff6da26c7f7]

goroutine 1 [running]:
database/sql.(*Stmt).Close(0x0)
        C:/Program Files/Go/src/database/sql/sql.go:2872 +0x37
panic({0x7ff6da80ae80, 0x7ff6da78d550})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
database/sql.(*Stmt).ExecContext(0x0, {0x7ff6da99e2c8, 0xc0000180a8}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/database/sql/sql.go:2619 +0x82
database/sql.(*Stmt).Exec(...)
        C:/Program Files/Go/src/database/sql/sql.go:2651
github.com/rikdata/ebs/db/sqlite.initServer()
        C:/Files/GitHub/s-goRest/db/sqlite/sqlite.go:60 +0x3bd
github.com/rikdata/ebs/db/sqlite.OpenDb()
        C:/Files/GitHub/s-goRest/db/sqlite/sqlite.go:34 +0xde
main.main()
        C:/Files/GitHub/s-goRest/main.go:62 +0x14f
